### ISSUE TITLE
its creating sitemap for one url only.

### ISSUE THREAD

**Issue by NileshDaldra** [spatie/laravel-sitemap#195] opened 2018-09-20 17:25 UTC
`SitemapGenerator::create("https://altcoincap.io/en")
            ->getSitemap()
            ->writeToFile($path);`
this creates
`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<url>
<loc>https://altcoincap.io/en</loc>
<lastmod>2018-09-20T17:23:05+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.8</priority>
</url>
</urlset>`
https://altcoincap.io/sitemap.xml
Can you guys help me?

**Comment by felixgoldstein** [comment] 2018-09-21 12:17
check if its disallowed in your robots.txt

**Comment by MichalOravec** [comment] 2018-09-21 19:19
I have same problem when using this package [https://github.com/mcamara/laravel-localization/](https://github.com/mcamara/laravel-localization/)

**Comment by NileshDaldra** [comment] 2018-09-22 15:02
@felixgoldstein  i have removed robots.txt but still same problem

**Comment by freekmurze** [comment] 2018-09-23 12:02
Duplicate of #174

Please check with curl if your website is giving the intended response.  

If there is something that our package can do better, please submit a PR.

**Closed by freekmurze** 2018-09-23 12:02 UTC

**Comment by minhdanh** [comment] 2019-05-25 14:40
> I have same problem when using this package https://github.com/mcamara/laravel-localization/

@michaloravec I'm using that package and having this problem too. Have you ever solved it?

**Comment by michaloravec** [comment] 2019-05-25 19:50
@minhdanh I'm no longer using this package. I programmed sitemap myself.
