### ISSUE TITLE
Empty sitemap

### ISSUE THREAD

**Issue by sergeevpasha** [spatie/laravel-sitemap#196] opened 2018-09-23 14:12 UTC
Hi, can you please help. Using php artisan sitemap:generate on localhost actually works great, while the same on a real web server returns nothing but:
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
</urlset>

```

What's the problem here?

**Comment by freekmurze** [comment] 2018-09-23 21:16
Duplicate of #179

**Closed by freekmurze** 2018-09-23 21:16 UTC

**Comment by sergeevpasha** [comment] 2018-10-16 13:45
sorry but i have no problems with robots, i dont even have robots.txt or any other restrictions. that's no help to me =(

**Comment by vanniewelt** [comment] 2019-02-04 17:58
Why are these issues closed with no resolution at all? I have same problem.

**Comment by romansidorov** [comment] 2019-09-24 12:48
> Why are these issues closed with no resolution at all? I have same problem.

Check option RequestOptions::ALLOW_REDIRECTS in sitemap.php and try to set it true.

**Comment by bsam2019** [comment] 2020-07-21 11:24
This is I solved this problem.

I just made sure APP_URL in .env file was set properly. I added, for example, https://example.com/, and boom it worked
